/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUIs;

import Model.Lesson;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.plaf.basic.BasicListUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kerem
 */
public class AddLessonI extends javax.swing.JInternalFrame {
Lesson lesson=new Lesson();
    /**
     * Creates new form AddLessonI
     */
    public AddLessonI() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui=(BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        
        lesData = new Object[4];
        lesModel=(DefaultTableModel) lesTable.getModel();
        for(int i=0;i<lesson.getLessonList().size();i++){
            lesData[0]=lesson.getLessonList().get(i).getId();
            lesData[1]=lesson.getLessonList().get(i).getLessonName();
            lesData[2]=lesson.getLessonList().get(i).getQuota();
            lesData[3]=lesson.getLessonList().get(i).getClassName();
            lesModel.addRow(lesData);
             lesSel();
        }
      
        lessonSelUpdate();
    }
    
    public void updateLessonList(){
        DefaultTableModel clearTable=(DefaultTableModel) lesTable.getModel();
        clearTable.setRowCount(0);
        
         for(int i=0;i<lesson.getLessonList().size();i++){
            lesData[0]=lesson.getLessonList().get(i).getId();
            lesData[1]=lesson.getLessonList().get(i).getLessonName();
            lesData[2]=lesson.getLessonList().get(i).getQuota();
            lesData[3]=lesson.getLessonList().get(i).getClassName();
            lesModel.addRow(lesData);
        }
         
    }
   public void lesSel(){
        lesModel=(DefaultTableModel) lesTable.getModel();
        lesTable.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
              try{
                   denemeLbl.setVisible(false);
               denemeLbl.setText(lesModel.getValueAt(lesTable.getSelectedRow(),0).toString());
              }
              catch(Exception ex){
                  
              }
            }
        });
    
    }
    
    public void lessonSelUpdate(){
        lesTable.getModel().addTableModelListener(new TableModelListener() {
            @Override
            public void tableChanged(TableModelEvent e) {
               if(e.getType()==TableModelEvent.UPDATE){
                   int selID=Integer.parseInt(lesTable.getValueAt(lesTable.getSelectedRow(), 0).toString());
                   String selLessonName=lesTable.getValueAt(lesTable.getSelectedRow(), 1).toString();
                   int selQuota=Integer.parseInt(lesTable.getValueAt(lesTable.getSelectedRow(), 2).toString());
                   String selClassName=lesTable.getValueAt(lesTable.getSelectedRow(), 3).toString();
                   lesson.updateLesson(selID,selLessonName, selQuota,selClassName);
               }
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addLesPnl = new javax.swing.JPanel();
        lesScroolPane = new javax.swing.JScrollPane();
        lesTable = new javax.swing.JTable();
        mGuiAddLesNameLbl = new javax.swing.JLabel();
        mGuiAddLesNameTxt = new javax.swing.JTextField();
        mGuiAddLesQuotaLbl = new javax.swing.JLabel();
        mGuiAddLesQuotaTxt = new javax.swing.JTextField();
        mGuiAddLesBtn = new javax.swing.JButton();
        mGuiDelLesBtn = new javax.swing.JButton();
        denemeLbl = new javax.swing.JLabel();
        mGuiAddLesClassLbl = new javax.swing.JLabel();
        mGuiAddLesClassCB = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(102, 0, 0));
        setOpaque(true);
        setPreferredSize(new java.awt.Dimension(500, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addLesPnl.setBackground(new java.awt.Color(255, 51, 51));
        addLesPnl.setMinimumSize(new java.awt.Dimension(510, 400));
        addLesPnl.setPreferredSize(new java.awt.Dimension(510, 400));
        addLesPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lesScroolPane.setBackground(new java.awt.Color(102, 0, 0));

        lesTable.setBackground(new java.awt.Color(102, 0, 0));
        lesTable.setForeground(new java.awt.Color(255, 255, 255));
        lesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Ders Adı", "Kontenjan","Bölüm"
            }
        ));
        lesTable.setSelectionBackground(new java.awt.Color(255, 102, 102));
        lesTable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        lesScroolPane.setViewportView(lesTable);

        addLesPnl.add(lesScroolPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 180));

        mGuiAddLesNameLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mGuiAddLesNameLbl.setText("DERS ADI");
        addLesPnl.add(mGuiAddLesNameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 100, 30));

        mGuiAddLesNameTxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addLesPnl.add(mGuiAddLesNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 100, 30));

        mGuiAddLesQuotaLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mGuiAddLesQuotaLbl.setText("KONTENJAN");
        addLesPnl.add(mGuiAddLesQuotaLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 100, 30));

        mGuiAddLesQuotaTxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addLesPnl.add(mGuiAddLesQuotaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 100, 30));

        mGuiAddLesBtn.setBackground(new java.awt.Color(102, 0, 0));
        mGuiAddLesBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mGuiAddLesBtn.setText("EKLE");
        mGuiAddLesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mGuiAddLesBtnActionPerformed(evt);
            }
        });
        addLesPnl.add(mGuiAddLesBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 100, 30));

        mGuiDelLesBtn.setBackground(new java.awt.Color(102, 0, 0));
        mGuiDelLesBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mGuiDelLesBtn.setText("SİL");
        mGuiDelLesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mGuiDelLesBtnActionPerformed(evt);
            }
        });
        addLesPnl.add(mGuiDelLesBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 100, 30));
        addLesPnl.add(denemeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 100, 10));

        mGuiAddLesClassLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mGuiAddLesClassLbl.setText("BÖLÜM");
        addLesPnl.add(mGuiAddLesClassLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 100, 30));

        mGuiAddLesClassCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elektrik-Elektronik", "Bilgisayar", "Yazılım", "Tekstil" }));
        addLesPnl.add(mGuiAddLesClassCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 110, 30));

        getContentPane().add(addLesPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mGuiAddLesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mGuiAddLesBtnActionPerformed

        if(mGuiAddLesNameTxt.getText().equals("")||mGuiAddLesQuotaTxt.getText().equals("")){
           Helper.OptionPane.showMessage("fill");
       }
       else{
                 int kota=Integer.parseInt(mGuiAddLesQuotaTxt.getText()) ;
           boolean control=lesson.addLesson(mGuiAddLesNameTxt.getText(),kota, (String) mGuiAddLesClassCB.getSelectedItem());
           if(control==true){
               Helper.OptionPane.showMessage("success");
               mGuiAddLesNameTxt.setText(null);
               mGuiAddLesQuotaTxt.setText(null);
               updateLessonList();
           }
       }
    }//GEN-LAST:event_mGuiAddLesBtnActionPerformed

    private void mGuiDelLesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mGuiDelLesBtnActionPerformed
           if(denemeLbl.getText().length()==0){
             Helper.OptionPane.showMessage("select");
             }
             else  {
          int selID=Integer.parseInt(denemeLbl.getText());
           
                boolean control=lesson.delLesson(selID);
                if(control==true){
                    Helper.OptionPane.showMessage("success");
                    denemeLbl.setText("");
                    updateLessonList();
                }
                else{
                    Helper.OptionPane.showMessage("error");
                     }
        
        }
        
    }//GEN-LAST:event_mGuiDelLesBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addLesPnl;
    private javax.swing.JLabel denemeLbl;
    private javax.swing.JScrollPane lesScroolPane;
    private javax.swing.JTable lesTable;
    private javax.swing.JButton mGuiAddLesBtn;
    private javax.swing.JComboBox<String> mGuiAddLesClassCB;
    private javax.swing.JLabel mGuiAddLesClassLbl;
    private javax.swing.JLabel mGuiAddLesNameLbl;
    private javax.swing.JTextField mGuiAddLesNameTxt;
    private javax.swing.JLabel mGuiAddLesQuotaLbl;
    private javax.swing.JTextField mGuiAddLesQuotaTxt;
    private javax.swing.JButton mGuiDelLesBtn;
    // End of variables declaration//GEN-END:variables
    private Object[] lesData=null;
    private DefaultTableModel lesModel=null;


}
