/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUIs;

import static GUIs.AddTeacherI.teacher;
import Model.Student;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kerem
 */
public class AddStudentI extends javax.swing.JInternalFrame {
Student student=new Student();
ManagerGUI mGUI=new ManagerGUI();
    /**
     * Creates new form AddStudentI
     */
    public AddStudentI() {
        initComponents();
           this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui=(BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        
            studentData=new Object[7];
            studentModel=(DefaultTableModel) stuTable.getModel();
            for(int i=0;i<student.getStudentList().size();i++){
            studentData[0]=student.getStudentList().get(i).getId();
            studentData[1]=student.getStudentList().get(i).getName();
            studentData[2]=student.getStudentList().get(i).getTcno();
            studentData[3]=student.getStudentList().get(i).getPassword();
            studentData[4]=student.getStudentList().get(i).getshNumber();
            studentData[5]=student.getStudentList().get(i).getClasses();
            studentData[6]=student.getStudentList().get(i).getGender();
            studentModel.addRow(studentData);
            stuSel();
            }
            studentSelUpdate();
    }
    
    public void studentSelUpdate(){
       stuTable.getModel().addTableModelListener(new TableModelListener() {
           @Override
           public void tableChanged(TableModelEvent e) {
              if(e.getType()==TableModelEvent.UPDATE){
                  int selID=Integer.parseInt(stuTable.getValueAt(stuTable.getSelectedRow(), 0).toString());
                  String selName=stuTable.getValueAt(stuTable.getSelectedRow(), 1).toString();
                  String selTcno=stuTable.getValueAt(stuTable.getSelectedRow(), 2).toString();
                  String selPass=stuTable.getValueAt(stuTable.getSelectedRow(), 3).toString();
                  String selShNumber=stuTable.getValueAt(stuTable.getSelectedRow(), 4).toString();
                  String selClasses=stuTable.getValueAt(stuTable.getSelectedRow(), 5).toString();
                  String selGender=stuTable.getValueAt(stuTable.getSelectedRow(), 6).toString();
                  student.updateStudent(selName, selTcno, selPass, selShNumber, selClasses, selGender);
              }
           }
       });
    }
    
public void updateStuTable(){
    DefaultTableModel clearTable=(DefaultTableModel) stuTable.getModel();
    clearTable.setRowCount(0);
    for(int i=0;i<student.getStudentList().size();i++){
            studentData[0]=student.getStudentList().get(i).getId();
            studentData[1]=student.getStudentList().get(i).getName();
            studentData[2]=student.getStudentList().get(i).getTcno();
            studentData[3]=student.getStudentList().get(i).getPassword();
              studentData[4]=student.getStudentList().get(i).getshNumber();
               studentData[5]=student.getStudentList().get(i).getClasses();
               studentData[6]=student.getStudentList().get(i).getGender();
            studentModel.addRow(studentData);
            }
}
public void stuSel(){
    stuTable.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
        @Override
        public void valueChanged(ListSelectionEvent e) {
            try{
            stuLbl.setVisible(false);
           stuLbl.setText(stuTable.getValueAt(stuTable.getSelectedRow() ,0).toString());
        }
            catch(Exception ex){
            }
            }
    });
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        addStudentPnl = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        stuTable = new javax.swing.JTable();
        mGuiAddStuNameLbl = new javax.swing.JLabel();
        mGuiAddStuTcnoLbl = new javax.swing.JLabel();
        mGuiAddStuPassLbl = new javax.swing.JLabel();
        mGuiAddStuSNoLbl = new javax.swing.JLabel();
        mGuiAddStuNameTxt = new javax.swing.JTextField();
        mGuiAddStuTcnoTxt = new javax.swing.JTextField();
        mGuiAddStuPassTxt = new javax.swing.JTextField();
        mGuiAddStuManRB = new javax.swing.JRadioButton();
        mGuiAddStuSNoTxt = new javax.swing.JTextField();
        mGuiAddStuWomanRB = new javax.swing.JRadioButton();
        mGuiAddStuBtn = new javax.swing.JButton();
        mGuiDelStuBtn = new javax.swing.JButton();
        mGuiAddStuClassLbl = new javax.swing.JLabel();
        stuLbl = new javax.swing.JLabel();
        classesCB = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(102, 0, 0));
        setMinimumSize(new java.awt.Dimension(500, 400));
        setPreferredSize(new java.awt.Dimension(500, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addStudentPnl.setBackground(new java.awt.Color(255, 51, 51));
        addStudentPnl.setMinimumSize(new java.awt.Dimension(500, 400));
        addStudentPnl.setPreferredSize(new java.awt.Dimension(500, 400));
        addStudentPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(102, 0, 0));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(500, 400));

        stuTable.setBackground(new java.awt.Color(102, 0, 0));
        stuTable.setForeground(new java.awt.Color(255, 255, 255));
        stuTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "ID", "Adı Soyadı", "TC Numarası", "Password","Okul No","Sınıf","Cinsiyet"
            }
        ));
        stuTable.setGridColor(new java.awt.Color(102, 0, 0));
        stuTable.setSelectionBackground(new java.awt.Color(255, 51, 51));
        stuTable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(stuTable);

        addStudentPnl.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 500, 180));

        mGuiAddStuNameLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mGuiAddStuNameLbl.setText("ADI SOYADI");
        addStudentPnl.add(mGuiAddStuNameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 100, 30));

        mGuiAddStuTcnoLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mGuiAddStuTcnoLbl.setText("T.C. NUMARASI");
        addStudentPnl.add(mGuiAddStuTcnoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 100, 30));

        mGuiAddStuPassLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mGuiAddStuPassLbl.setText("ŞİFRE");
        addStudentPnl.add(mGuiAddStuPassLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 100, 30));

        mGuiAddStuSNoLbl.setBackground(new java.awt.Color(255, 51, 51));
        mGuiAddStuSNoLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mGuiAddStuSNoLbl.setText("OKUL NO");
        addStudentPnl.add(mGuiAddStuSNoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 100, 30));

        mGuiAddStuNameTxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addStudentPnl.add(mGuiAddStuNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 100, 30));

        mGuiAddStuTcnoTxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addStudentPnl.add(mGuiAddStuTcnoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 100, 30));

        mGuiAddStuPassTxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addStudentPnl.add(mGuiAddStuPassTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 100, 30));

        buttonGroup1.add(mGuiAddStuManRB);
        mGuiAddStuManRB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mGuiAddStuManRB.setText("ERKEK");
        mGuiAddStuManRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mGuiAddStuManRBActionPerformed(evt);
            }
        });
        addStudentPnl.add(mGuiAddStuManRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, -1, -1));

        mGuiAddStuSNoTxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addStudentPnl.add(mGuiAddStuSNoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 100, 30));

        buttonGroup1.add(mGuiAddStuWomanRB);
        mGuiAddStuWomanRB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mGuiAddStuWomanRB.setText("KADIN");
        mGuiAddStuWomanRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mGuiAddStuWomanRBActionPerformed(evt);
            }
        });
        addStudentPnl.add(mGuiAddStuWomanRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, -1, -1));

        mGuiAddStuBtn.setBackground(new java.awt.Color(102, 0, 0));
        mGuiAddStuBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mGuiAddStuBtn.setText("EKLE");
        mGuiAddStuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mGuiAddStuBtnActionPerformed(evt);
            }
        });
        addStudentPnl.add(mGuiAddStuBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 100, 30));

        mGuiDelStuBtn.setBackground(new java.awt.Color(102, 0, 0));
        mGuiDelStuBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mGuiDelStuBtn.setText("SİL");
        mGuiDelStuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mGuiDelStuBtnActionPerformed(evt);
            }
        });
        addStudentPnl.add(mGuiDelStuBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 100, 30));

        mGuiAddStuClassLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mGuiAddStuClassLbl.setText("SINIF");
        addStudentPnl.add(mGuiAddStuClassLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 100, 30));
        addStudentPnl.add(stuLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 50, 30));

        classesCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elektrik-Elektronik", "Bilgisayar", "Yazılım", "Tekstil" }));
        addStudentPnl.add(classesCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, 30));

        getContentPane().add(addStudentPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 510, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mGuiAddStuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mGuiAddStuBtnActionPerformed
            if(mGuiAddStuNameTxt.getText().equals("")||mGuiAddStuPassTxt.getText().equals("")||mGuiAddStuTcnoTxt.getText().equals("")||mGuiAddStuSNoTxt.getText().equals("")){
            Helper.OptionPane.showMessage("fill");
        }
        else{
             boolean control=student.addStudent(mGuiAddStuNameTxt.getText(),mGuiAddStuTcnoTxt.getText(), mGuiAddStuPassTxt.getText(), mGuiAddStuSNoTxt.getText(), (String) classesCB.getSelectedItem(),Bg2);
            if(control==true){
                Helper.OptionPane.showMessage("success");
                mGuiAddStuNameTxt.setText(null);
                mGuiAddStuTcnoTxt.setText(null);
                mGuiAddStuPassTxt.setText(null);
                mGuiAddStuSNoTxt.setText(null);
                
               mGuiAddStuManRB.setSelected(false);
               mGuiAddStuWomanRB.setSelected(false);
               
               
                updateStuTable();
               
            }
        }
    }//GEN-LAST:event_mGuiAddStuBtnActionPerformed

    private void mGuiDelStuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mGuiDelStuBtnActionPerformed
        
       
        if(stuLbl.getText().equals("")){
            Helper.OptionPane.showMessage("select");
        }
        else{
             int selID=Integer.parseInt(stuLbl.getText()) ;
          
                boolean control=student.delStudent(selID);
                if(control==true){
                    Helper.OptionPane.showMessage("success");
                    stuLbl.setText("");
                    updateStuTable();
                }
           
        }
       
    }//GEN-LAST:event_mGuiDelStuBtnActionPerformed

    private void mGuiAddStuManRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mGuiAddStuManRBActionPerformed
       Bg2="ERKEK";
    }//GEN-LAST:event_mGuiAddStuManRBActionPerformed

    private void mGuiAddStuWomanRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mGuiAddStuWomanRBActionPerformed
       Bg2="KADIN";
    }//GEN-LAST:event_mGuiAddStuWomanRBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addStudentPnl;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> classesCB;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mGuiAddStuBtn;
    private javax.swing.JLabel mGuiAddStuClassLbl;
    private javax.swing.JRadioButton mGuiAddStuManRB;
    private javax.swing.JLabel mGuiAddStuNameLbl;
    private javax.swing.JTextField mGuiAddStuNameTxt;
    private javax.swing.JLabel mGuiAddStuPassLbl;
    private javax.swing.JTextField mGuiAddStuPassTxt;
    private javax.swing.JLabel mGuiAddStuSNoLbl;
    private javax.swing.JTextField mGuiAddStuSNoTxt;
    private javax.swing.JLabel mGuiAddStuTcnoLbl;
    private javax.swing.JTextField mGuiAddStuTcnoTxt;
    private javax.swing.JRadioButton mGuiAddStuWomanRB;
    private javax.swing.JButton mGuiDelStuBtn;
    private javax.swing.JLabel stuLbl;
    private javax.swing.JTable stuTable;
    // End of variables declaration//GEN-END:variables
private String Bg2="ERKEK";
        Object[] studentData=null;
        DefaultTableModel studentModel=null;
        
        }
