/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUIs;

import Helper.DBConnection;
import Model.Student;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kerem
 */
public class ClassesBilI extends javax.swing.JInternalFrame {

    /**
     * Creates new form ClassesBilI
     */
    public ClassesBilI() {
        initComponents();
          this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui=(BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        
        
        bilData=new Object[4];
       bilModel=(DefaultTableModel)BilTable.getModel();
       for(int i=0;i<getClassesBillist().size();i++){
           bilData[0]=getClassesBillist().get(i).getId();
           bilData[1]=getClassesBillist().get(i).getName();
           bilData[2]=getClassesBillist().get(i).getshNumber();
           bilData[3]=getClassesBillist().get(i).getClasses();
           bilModel.addRow(bilData);
           
       }
    }
    
    
    public ArrayList<Student> getClassesBillist(){
        ArrayList<Student> list =new ArrayList<>();
            Student obj;
        try {
            
            String query="SELECT*FROM student WHERE classes='Bilgisayar'";
            st=con.createStatement();
            rs=st.executeQuery(query);
            while(rs.next()){
                obj=new Student(rs.getInt("id"),rs.getString("name"),rs.getString("tcno"),rs.getString("password"),rs.getString("shNumber"),rs.getString("classes"),rs.getString("gender"));
                list.add(obj);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ClassesI.class.getName()).log(Level.SEVERE, null, ex);
        }
        return list;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BilPnl = new javax.swing.JPanel();
        Bil = new javax.swing.JScrollPane();
        BilTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 51, 51));
        setOpaque(true);
        setPreferredSize(new java.awt.Dimension(500, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BilPnl.setBackground(new java.awt.Color(255, 51, 51));

        Bil.setBackground(new java.awt.Color(255, 51, 51));
        Bil.setForeground(new java.awt.Color(255, 255, 255));
        Bil.setPreferredSize(new java.awt.Dimension(300, 400));

        BilTable.setBackground(new java.awt.Color(255, 51, 51));
        BilTable.setForeground(new java.awt.Color(255, 255, 255));
        BilTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Adı Soyadı", "Okul NO", "Sınıf"
            }
        ));
        Bil.setViewportView(BilTable);

        javax.swing.GroupLayout BilPnlLayout = new javax.swing.GroupLayout(BilPnl);
        BilPnl.setLayout(BilPnlLayout);
        BilPnlLayout.setHorizontalGroup(
            BilPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BilPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Bil, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );
        BilPnlLayout.setVerticalGroup(
            BilPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BilPnlLayout.createSequentialGroup()
                .addComponent(Bil, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(BilPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 500, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane Bil;
    private javax.swing.JPanel BilPnl;
    private javax.swing.JTable BilTable;
    // End of variables declaration//GEN-END:variables
    Object[] bilData=null;
    DefaultTableModel bilModel=null;
    private DBConnection conn=new DBConnection();
    private  Connection con=conn.connDB();
    private  Statement st=null;
    private   ResultSet rs=null;
    private   PreparedStatement pt=null;
        }
