/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUIs;

import Helper.DBConnection;
import Model.Student;
import java.sql.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Kerem
 */
public class ClassesI extends javax.swing.JInternalFrame {

    /**
     * Creates new form ClassesI
     */
    public ClassesI() {
        initComponents();
         this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui=(BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
    }
   
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        teachClassesPnl = new javax.swing.JPanel();
        ClassesCB = new javax.swing.JComboBox<>();
        ClassesDP = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 0, 0));
        setOpaque(true);
        setPreferredSize(new java.awt.Dimension(500, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        teachClassesPnl.setBackground(new java.awt.Color(102, 0, 0));
        teachClassesPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ClassesCB.setBackground(new java.awt.Color(0, 0, 0));
        ClassesCB.setForeground(new java.awt.Color(255, 255, 255));
        ClassesCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elektrik-Elektronik", "Bilgisayar", "Yazılım", "Tekstil" }));
        ClassesCB.setOpaque(true);
        ClassesCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClassesCBActionPerformed(evt);
            }
        });
        teachClassesPnl.add(ClassesCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 100, -1));

        ClassesDP.setBackground(new java.awt.Color(102, 0, 0));

        javax.swing.GroupLayout ClassesDPLayout = new javax.swing.GroupLayout(ClassesDP);
        ClassesDP.setLayout(ClassesDPLayout);
        ClassesDPLayout.setHorizontalGroup(
            ClassesDPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 378, Short.MAX_VALUE)
        );
        ClassesDPLayout.setVerticalGroup(
            ClassesDPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 355, Short.MAX_VALUE)
        );

        teachClassesPnl.add(ClassesDP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BÖLÜM SEÇİNİZ");
        teachClassesPnl.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 16, 100, 20));

        getContentPane().add(teachClassesPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClassesCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClassesCBActionPerformed
        if(ClassesCB.getSelectedItem().equals("Elektrik-Elektronik")){
            ClassesElekI elek=new ClassesElekI();
            ClassesDP.removeAll();
            ClassesDP.add(elek).setVisible(true);
        }
        else  if(ClassesCB.getSelectedItem().equals("Bilgisayar")){
            ClassesBilI bil=new ClassesBilI();
            ClassesDP.removeAll();
            ClassesDP.add(bil).setVisible(true);
        }
        else if(ClassesCB.getSelectedItem().equals("Yazılım")){
            ClassesYazI yaz=new ClassesYazI();
            ClassesDP.removeAll();
            ClassesDP.add(yaz).setVisible(true);
        }
        else if(ClassesCB.getSelectedItem().equals("Tekstil")){
            ClassesTeksI teks=new ClassesTeksI();
            ClassesDP.removeAll();
            ClassesDP.add(teks).setVisible(true);
        }
    }//GEN-LAST:event_ClassesCBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ClassesCB;
    private javax.swing.JDesktopPane ClassesDP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel teachClassesPnl;
    // End of variables declaration//GEN-END:variables


}
