/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUIs;

import Helper.DBConnection;
import Model.Student;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kerem
 */
public class ClassesYazI extends javax.swing.JInternalFrame {

    /**
     * Creates new form ClassesYazI
     */
    public ClassesYazI() {
        initComponents();
          this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui=(BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        
        
         yazData=new Object[4];
       yazModel=(DefaultTableModel) YazTable.getModel();
       for(int i=0;i<getClassesYazlist().size();i++){
           yazData[0]=getClassesYazlist().get(i).getId();
           yazData[1]=getClassesYazlist().get(i).getName();
           yazData[2]=getClassesYazlist().get(i).getshNumber();
           yazData[3]=getClassesYazlist().get(i).getClasses();
           yazModel.addRow(yazData);
           
       }
    }
    public ArrayList<Student> getClassesYazlist(){
        ArrayList<Student> list =new ArrayList<>();
            Student obj;
        try {
            
            String query="SELECT*FROM student WHERE classes='Yazılım'";
            st=con.createStatement();
            rs=st.executeQuery(query);
            while(rs.next()){
                obj=new Student(rs.getInt("id"),rs.getString("name"),rs.getString("tcno"),rs.getString("password"),rs.getString("shNumber"),rs.getString("classes"),rs.getString("gender"));
                list.add(obj);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ClassesI.class.getName()).log(Level.SEVERE, null, ex);
        }
        return list;
    }
       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        YazPnl = new javax.swing.JPanel();
        Yaz = new javax.swing.JScrollPane();
        YazTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 51, 51));
        setOpaque(true);
        setPreferredSize(new java.awt.Dimension(500, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        YazPnl.setBackground(new java.awt.Color(255, 51, 51));
        YazPnl.setPreferredSize(new java.awt.Dimension(500, 400));

        Yaz.setBackground(new java.awt.Color(255, 51, 51));
        Yaz.setPreferredSize(new java.awt.Dimension(500, 350));

        YazTable.setBackground(new java.awt.Color(255, 51, 51));
        YazTable.setForeground(new java.awt.Color(255, 255, 255));
        YazTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Adı Soyadı", "Okul NO", "Sınıf"
            }
        ));
        Yaz.setViewportView(YazTable);

        javax.swing.GroupLayout YazPnlLayout = new javax.swing.GroupLayout(YazPnl);
        YazPnl.setLayout(YazPnlLayout);
        YazPnlLayout.setHorizontalGroup(
            YazPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(YazPnlLayout.createSequentialGroup()
                .addComponent(Yaz, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 120, Short.MAX_VALUE))
        );
        YazPnlLayout.setVerticalGroup(
            YazPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(YazPnlLayout.createSequentialGroup()
                .addComponent(Yaz, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(YazPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane Yaz;
    private javax.swing.JPanel YazPnl;
    private javax.swing.JTable YazTable;
    // End of variables declaration//GEN-END:variables
    Object[] yazData=null;
    DefaultTableModel yazModel=null;
    private DBConnection conn=new DBConnection();
    private  Connection con=conn.connDB();
    private  Statement st=null;
    private   ResultSet rs=null;
    private   PreparedStatement pt=null;
}
