/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUIs;

import static GUIs.LoginGUI.studentData;
import Helper.DBConnection;
import Model.Classes;
import Model.Student;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kerem
 */
public class ClassesElekI extends javax.swing.JInternalFrame {
ClassesI classesI=new ClassesI();
    /**
     * Creates new form ClassesElekI
     */
    public ClassesElekI() {
        initComponents();
          this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui=(BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        
       elekData=new Object[4];
       elekModel=(DefaultTableModel) ElekTable.getModel();
       for(int i=0;i<getClassesEleklist().size();i++){
           elekData[0]=getClassesEleklist().get(i).getId();
           elekData[1]=getClassesEleklist().get(i).getName();
           elekData[2]=getClassesEleklist().get(i).getshNumber();
           elekData[3]=getClassesEleklist().get(i).getClasses();
           elekModel.addRow(elekData);
           
       }
    }
    public ArrayList<Student> getClassesEleklist(){
        ArrayList<Student> list =new ArrayList<>();
            Student obj;
        try {
            
            String query="SELECT*FROM student WHERE classes='Elektrik-Elektronik'";
            st=con.createStatement();
            rs=st.executeQuery(query);
            while(rs.next()){
                obj=new Student(rs.getInt("id"),rs.getString("name"),rs.getString("tcno"),rs.getString("password"),rs.getString("shNumber"),rs.getString("classes"),rs.getString("gender"));
                list.add(obj);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ClassesI.class.getName()).log(Level.SEVERE, null, ex);
        }
        return list;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ElekPnl = new javax.swing.JPanel();
        Elek = new javax.swing.JScrollPane();
        ElekTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 51, 51));
        setOpaque(true);
        setPreferredSize(new java.awt.Dimension(500, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ElekPnl.setBackground(new java.awt.Color(255, 51, 51));

        Elek.setBackground(new java.awt.Color(255, 51, 51));
        Elek.setMinimumSize(new java.awt.Dimension(10, 16));
        Elek.setPreferredSize(new java.awt.Dimension(500, 400));

        ElekTable.setBackground(new java.awt.Color(255, 51, 51));
        ElekTable.setForeground(new java.awt.Color(255, 255, 255));
        ElekTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Adı Soyadı", "Okul NO", "Sınıf"
            }
        ));
        ElekTable.setGridColor(new java.awt.Color(255, 255, 255));
        ElekTable.setSelectionBackground(new java.awt.Color(255, 51, 51));
        ElekTable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        Elek.setViewportView(ElekTable);

        javax.swing.GroupLayout ElekPnlLayout = new javax.swing.GroupLayout(ElekPnl);
        ElekPnl.setLayout(ElekPnlLayout);
        ElekPnlLayout.setHorizontalGroup(
            ElekPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ElekPnlLayout.createSequentialGroup()
                .addComponent(Elek, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 105, Short.MAX_VALUE))
        );
        ElekPnlLayout.setVerticalGroup(
            ElekPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ElekPnlLayout.createSequentialGroup()
                .addComponent(Elek, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        getContentPane().add(ElekPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane Elek;
    private javax.swing.JPanel ElekPnl;
    private javax.swing.JTable ElekTable;
    // End of variables declaration//GEN-END:variables
    Object[] elekData=null;
    DefaultTableModel elekModel=null;
    private DBConnection conn=new DBConnection();
    private  Connection con=conn.connDB();
    private  Statement st=null;
    private   ResultSet rs=null;
    private   PreparedStatement pt=null;
}
