/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUIs;

import static GUIs.LoginGUI.managerData;
import static GUIs.LoginGUI.studentData;
import static GUIs.LoginGUI.teacherData;
import Helper.DBConnection;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import Model.*;
import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kerem
 */
public class ManagerGUI extends javax.swing.JFrame {

    static Teacher teacher = new Teacher();

    /**
     * Creates new form TeacherGUI
     */
    public ManagerGUI() {

        try {

            initComponents();
            
            st = con.createStatement();
            rs = st.executeQuery("SELECT*FROM teacher");
            while (rs.next()) {
                mGuiWelcomeLbl.setText("Hoşgeldiniz " + managerData[1]);
                if(managerData[5].equals("ERKEK")){
                       
                    mGuiIconLbl.setIcon(new ImageIcon("C:\\swingDemos\\SchoolProject\\src\\Img\\yerkek.png"));
                    
                }
                else if(managerData[5].equals("KADIN")){
                
    ImageIcon teachWoman = new ImageIcon("C:\\swingDemos\\SchoolProject\\src\\Img\\ykadin.png");
                     mGuiIconLbl.setIcon(teachWoman);
                     
                }
                else{
                    Helper.OptionPane.showMessage("error");
                }
            }

        } catch (SQLException ex) {
            Logger.getLogger(ManagerGUI.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mGuiMainPnl = new javax.swing.JPanel();
        mGuiTopPnl = new javax.swing.JPanel();
        mGuiTopLbl = new javax.swing.JLabel();
        mGuiLeftPnl = new javax.swing.JPanel();
        mGuiLeftTopPnl = new javax.swing.JPanel();
        mGuiIconLbl = new javax.swing.JLabel();
        mGuiWelcomeLbl = new javax.swing.JLabel();
        mGuiLeftDownPnl = new javax.swing.JPanel();
        mGuiAddTeachPnl = new javax.swing.JPanel();
        mGuiAddTeachLbl = new javax.swing.JLabel();
        mGuiAddStudentPnl = new javax.swing.JPanel();
        mGuiAddStudentLbl = new javax.swing.JLabel();
        mGuiAddClassPnl = new javax.swing.JPanel();
        mGuiAddLessonLbl = new javax.swing.JLabel();
        LogOutLbl = new javax.swing.JLabel();
        LogOutLbl1 = new javax.swing.JLabel();
        mGuiTeachtoLesson = new javax.swing.JPanel();
        mGuiTeachtoLessonLbl = new javax.swing.JLabel();
        mGuiDesktopPane = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 0, 0));
        setMinimumSize(new java.awt.Dimension(700, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(700, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mGuiMainPnl.setBackground(new java.awt.Color(255, 255, 255));
        mGuiMainPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mGuiTopPnl.setBackground(new java.awt.Color(102, 0, 0));
        mGuiTopPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mGuiTopLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mGuiTopLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIs/Images/teacher page 500X100 .png"))); // NOI18N
        mGuiTopLbl.setText("tGuiTopLbl");
        mGuiTopPnl.add(mGuiTopLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 100));

        mGuiMainPnl.add(mGuiTopPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 500, 100));

        mGuiLeftPnl.setBackground(new java.awt.Color(102, 0, 0));
        mGuiLeftPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mGuiLeftTopPnl.setBackground(new java.awt.Color(102, 0, 0));
        mGuiLeftTopPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mGuiIconLbl.setBackground(new java.awt.Color(102, 0, 0));
        mGuiIconLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mGuiIconLbl.setMaximumSize(new java.awt.Dimension(200, 60));
        mGuiIconLbl.setOpaque(true);
        mGuiIconLbl.setPreferredSize(new java.awt.Dimension(200, 60));
        mGuiLeftTopPnl.add(mGuiIconLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 60));

        mGuiWelcomeLbl.setBackground(new java.awt.Color(102, 0, 0));
        mGuiWelcomeLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mGuiWelcomeLbl.setForeground(new java.awt.Color(255, 255, 255));
        mGuiWelcomeLbl.setText("Hoşgeldiniz ");
        mGuiWelcomeLbl.setOpaque(true);
        mGuiLeftTopPnl.add(mGuiWelcomeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 200, 40));

        mGuiLeftPnl.add(mGuiLeftTopPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 160));

        mGuiLeftDownPnl.setBackground(new java.awt.Color(102, 0, 0));
        mGuiLeftDownPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mGuiAddTeachPnl.setBackground(new java.awt.Color(102, 0, 0));
        mGuiAddTeachPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mGuiAddTeachLbl.setBackground(new java.awt.Color(102, 0, 0));
        mGuiAddTeachLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mGuiAddTeachLbl.setForeground(new java.awt.Color(255, 255, 255));
        mGuiAddTeachLbl.setText("Öğretmen Ekleme");
        mGuiAddTeachLbl.setOpaque(true);
        mGuiAddTeachLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mGuiAddTeachLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mGuiAddTeachLblMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mGuiAddTeachLblMousePressed(evt);
            }
        });
        mGuiAddTeachPnl.add(mGuiAddTeachLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 40));

        mGuiLeftDownPnl.add(mGuiAddTeachPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 40));

        mGuiAddStudentPnl.setBackground(new java.awt.Color(102, 0, 0));
        mGuiAddStudentPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mGuiAddStudentLbl.setBackground(new java.awt.Color(102, 0, 0));
        mGuiAddStudentLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mGuiAddStudentLbl.setForeground(new java.awt.Color(255, 255, 255));
        mGuiAddStudentLbl.setText("Öğrenci Ekleme");
        mGuiAddStudentLbl.setOpaque(true);
        mGuiAddStudentLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mGuiAddStudentLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mGuiAddStudentLblMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mGuiAddStudentLblMousePressed(evt);
            }
        });
        mGuiAddStudentPnl.add(mGuiAddStudentLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 40));

        mGuiLeftDownPnl.add(mGuiAddStudentPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 200, 40));

        mGuiAddClassPnl.setBackground(new java.awt.Color(0, 117, 238));
        mGuiAddClassPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mGuiAddLessonLbl.setBackground(new java.awt.Color(102, 0, 0));
        mGuiAddLessonLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mGuiAddLessonLbl.setForeground(new java.awt.Color(255, 255, 255));
        mGuiAddLessonLbl.setText("Ders Ekleme");
        mGuiAddLessonLbl.setOpaque(true);
        mGuiAddLessonLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mGuiAddLessonLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mGuiAddLessonLblMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mGuiAddLessonLblMousePressed(evt);
            }
        });
        mGuiAddClassPnl.add(mGuiAddLessonLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 40));

        LogOutLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogOutLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIs/Images/logout (4).png"))); // NOI18N
        mGuiAddClassPnl.add(LogOutLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 40, 30));

        mGuiLeftDownPnl.add(mGuiAddClassPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 200, 40));

        LogOutLbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogOutLbl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIs/Images/logout (4).png"))); // NOI18N
        LogOutLbl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LogOutLbl1MousePressed(evt);
            }
        });
        mGuiLeftDownPnl.add(LogOutLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 40, -1));

        mGuiTeachtoLesson.setBackground(new java.awt.Color(0, 117, 238));
        mGuiTeachtoLesson.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mGuiTeachtoLessonLbl.setBackground(new java.awt.Color(102, 0, 0));
        mGuiTeachtoLessonLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mGuiTeachtoLessonLbl.setForeground(new java.awt.Color(255, 255, 255));
        mGuiTeachtoLessonLbl.setText("Öğretmen Atama");
        mGuiTeachtoLessonLbl.setOpaque(true);
        mGuiTeachtoLessonLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mGuiTeachtoLessonLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mGuiTeachtoLessonLblMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mGuiTeachtoLessonLblMousePressed(evt);
            }
        });
        mGuiTeachtoLesson.add(mGuiTeachtoLessonLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 40));

        mGuiLeftDownPnl.add(mGuiTeachtoLesson, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 200, 40));

        mGuiLeftPnl.add(mGuiLeftDownPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 200, 350));

        mGuiMainPnl.add(mGuiLeftPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 500));

        mGuiDesktopPane.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout mGuiDesktopPaneLayout = new javax.swing.GroupLayout(mGuiDesktopPane);
        mGuiDesktopPane.setLayout(mGuiDesktopPaneLayout);
        mGuiDesktopPaneLayout.setHorizontalGroup(
            mGuiDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        mGuiDesktopPaneLayout.setVerticalGroup(
            mGuiDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        mGuiMainPnl.add(mGuiDesktopPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 500, 400));

        getContentPane().add(mGuiMainPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mGuiAddTeachLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mGuiAddTeachLblMouseEntered
        mGuiAddTeachLbl.setBackground(new Color(255, 51, 51));
    }//GEN-LAST:event_mGuiAddTeachLblMouseEntered

    private void mGuiAddTeachLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mGuiAddTeachLblMouseExited
        mGuiAddTeachLbl.setBackground(new Color(102, 0, 0));
    }//GEN-LAST:event_mGuiAddTeachLblMouseExited

    private void mGuiAddStudentLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mGuiAddStudentLblMouseEntered
        mGuiAddStudentLbl.setBackground(new Color(255, 51, 51));
    }//GEN-LAST:event_mGuiAddStudentLblMouseEntered

    private void mGuiAddStudentLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mGuiAddStudentLblMouseExited
        mGuiAddStudentLbl.setBackground(new Color(102, 0, 0));
    }//GEN-LAST:event_mGuiAddStudentLblMouseExited

    private void mGuiAddStudentLblMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mGuiAddStudentLblMousePressed
        AddStudentI addStu = new AddStudentI();
        mGuiDesktopPane.removeAll();
        mGuiDesktopPane.add(addStu).setVisible(true);    
    }//GEN-LAST:event_mGuiAddStudentLblMousePressed

    private void mGuiAddTeachLblMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mGuiAddTeachLblMousePressed
        AddTeacherI addTeach = new AddTeacherI();
        mGuiDesktopPane.removeAll();
        mGuiDesktopPane.add(addTeach).setVisible(true);
    }//GEN-LAST:event_mGuiAddTeachLblMousePressed

    private void mGuiAddLessonLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mGuiAddLessonLblMouseEntered
        mGuiAddLessonLbl.setBackground(new Color(255, 51, 51));
    }//GEN-LAST:event_mGuiAddLessonLblMouseEntered

    private void mGuiAddLessonLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mGuiAddLessonLblMouseExited
        mGuiAddLessonLbl.setBackground(new Color(102, 0, 0));
    }//GEN-LAST:event_mGuiAddLessonLblMouseExited

    private void mGuiAddLessonLblMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mGuiAddLessonLblMousePressed
        AddLessonI addLesson = new AddLessonI();
        mGuiDesktopPane.removeAll();
        mGuiDesktopPane.add(addLesson).setVisible(true);       
    }//GEN-LAST:event_mGuiAddLessonLblMousePressed

    private void LogOutLbl1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutLbl1MousePressed
        LoginGUI logOut=new LoginGUI();
        logOut.setVisible(true);
        dispose();       
    }//GEN-LAST:event_LogOutLbl1MousePressed

    private void mGuiTeachtoLessonLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mGuiTeachtoLessonLblMouseEntered
         mGuiTeachtoLessonLbl.setBackground(new Color(255, 51, 51));
    }//GEN-LAST:event_mGuiTeachtoLessonLblMouseEntered

    private void mGuiTeachtoLessonLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mGuiTeachtoLessonLblMouseExited
      mGuiTeachtoLessonLbl.setBackground(new Color(102, 0, 0));
    }//GEN-LAST:event_mGuiTeachtoLessonLblMouseExited

    private void mGuiTeachtoLessonLblMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mGuiTeachtoLessonLblMousePressed
       TeacherAssignmentI TTL = new TeacherAssignmentI();
        mGuiDesktopPane.removeAll();
        mGuiDesktopPane.add(TTL).setVisible(true);    
    }//GEN-LAST:event_mGuiTeachtoLessonLblMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ManagerGUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LogOutLbl;
    private javax.swing.JLabel LogOutLbl1;
    private javax.swing.JPanel mGuiAddClassPnl;
    private javax.swing.JLabel mGuiAddLessonLbl;
    private javax.swing.JLabel mGuiAddStudentLbl;
    private javax.swing.JPanel mGuiAddStudentPnl;
    private javax.swing.JLabel mGuiAddTeachLbl;
    private javax.swing.JPanel mGuiAddTeachPnl;
    private javax.swing.JDesktopPane mGuiDesktopPane;
    public javax.swing.JLabel mGuiIconLbl;
    private javax.swing.JPanel mGuiLeftDownPnl;
    private javax.swing.JPanel mGuiLeftPnl;
    private javax.swing.JPanel mGuiLeftTopPnl;
    private javax.swing.JPanel mGuiMainPnl;
    private javax.swing.JPanel mGuiTeachtoLesson;
    private javax.swing.JLabel mGuiTeachtoLessonLbl;
    private javax.swing.JLabel mGuiTopLbl;
    private javax.swing.JPanel mGuiTopPnl;
    private javax.swing.JLabel mGuiWelcomeLbl;
    // End of variables declaration//GEN-END:variables
DBConnection conn = new DBConnection();
Connection con=conn.connDB();
    Statement st = null;
    ResultSet rs = null;
    PreparedStatement pt = null;
    
 
}
