/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUIs;

import static GUIs.LoginGUI.studentData;
import Helper.DBConnection;
import Model.Student;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Kerem
 */
public class MyInfoI extends javax.swing.JInternalFrame {
Student student =new Student();

    /**
     * Creates new form MyInfoI
     */
    public MyInfoI() {
        initComponents();
         this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
            BasicInternalFrameUI ui=(BasicInternalFrameUI) this.getUI();
            ui.setNorthPane(null);
            studentInfo((String) studentData[2]);
   
    }
    public void studentInfo(String tcno){
             try {
            st=con.createStatement();
            rs=st.executeQuery("SELECT*FROM student WHERE tcno="+tcno);
            while(rs.next()){
                
                  myInfoNameAnsLbl.setText((String) studentData[1]);
               myInfoTcnoAnsLbl.setText((String) studentData[2]);
               
                myInfoPassAnsLbl.setText((String) studentData[3]);
                     myInfoShNumberAnsLbl.setText((String) studentData[4]);
               myInfoClassAnsLbl.setText((String) studentData[5]);
               myInfoGenderAnsLbl.setText((String) studentData[6]);
                if(studentData[6].equals("ERKEK")){
                     myInfoPhotoLbl.setIcon(new ImageIcon("C:\\swingDemos\\SchoolProject\\src\\Img\\erkek.png"));
                }
                else if(studentData[6].equals("KADIN")){
                    myInfoPhotoLbl.setIcon(new ImageIcon("C:\\swingDemos\\SchoolProject\\src\\Img\\kadin.png"));
                }
                else{
                    Helper.OptionPane.showMessage("error");
                }
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(MyInfoI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myInfoPnl = new javax.swing.JPanel();
        myInfoNameLbl = new javax.swing.JLabel();
        myInfoTcnoLbl = new javax.swing.JLabel();
        myInfoPassLbl = new javax.swing.JLabel();
        myInfoShNumberLbl = new javax.swing.JLabel();
        myInfoClassLbl = new javax.swing.JLabel();
        myInfoPhotoLbl = new javax.swing.JLabel();
        myInfoNameAnsLbl = new javax.swing.JLabel();
        myInfoTcnoAnsLbl = new javax.swing.JLabel();
        myInfoPassAnsLbl = new javax.swing.JLabel();
        myInfoShNumberAnsLbl = new javax.swing.JLabel();
        myInfoClassAnsLbl = new javax.swing.JLabel();
        myInfoGenderAnsLbl = new javax.swing.JLabel();
        myInfoGenderLbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 0, 0));
        setOpaque(true);
        setPreferredSize(new java.awt.Dimension(500, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        myInfoPnl.setBackground(new java.awt.Color(51, 0, 0));
        myInfoPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        myInfoNameLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        myInfoNameLbl.setForeground(new java.awt.Color(255, 255, 255));
        myInfoNameLbl.setText("ADI SOYADI");
        myInfoPnl.add(myInfoNameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 175, 30));

        myInfoTcnoLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        myInfoTcnoLbl.setForeground(new java.awt.Color(255, 255, 255));
        myInfoTcnoLbl.setText("T.C. NUMARASI");
        myInfoPnl.add(myInfoTcnoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 175, 30));

        myInfoPassLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        myInfoPassLbl.setForeground(new java.awt.Color(255, 255, 255));
        myInfoPassLbl.setText("ŞİFRE");
        myInfoPnl.add(myInfoPassLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 175, 30));

        myInfoShNumberLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        myInfoShNumberLbl.setForeground(new java.awt.Color(255, 255, 255));
        myInfoShNumberLbl.setText("OKUL NUMARASI");
        myInfoPnl.add(myInfoShNumberLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 175, 30));

        myInfoClassLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        myInfoClassLbl.setForeground(new java.awt.Color(255, 255, 255));
        myInfoClassLbl.setText("SINIFI");
        myInfoPnl.add(myInfoClassLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 175, 30));
        myInfoPnl.add(myInfoPhotoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 150, 100));

        myInfoNameAnsLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        myInfoNameAnsLbl.setForeground(new java.awt.Color(255, 255, 255));
        myInfoNameAnsLbl.setText("jLabel7");
        myInfoPnl.add(myInfoNameAnsLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 200, 30));

        myInfoTcnoAnsLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        myInfoTcnoAnsLbl.setForeground(new java.awt.Color(255, 255, 255));
        myInfoTcnoAnsLbl.setText("jLabel8");
        myInfoPnl.add(myInfoTcnoAnsLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 200, 30));

        myInfoPassAnsLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        myInfoPassAnsLbl.setForeground(new java.awt.Color(255, 255, 255));
        myInfoPassAnsLbl.setText("jLabel9");
        myInfoPnl.add(myInfoPassAnsLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 200, 30));

        myInfoShNumberAnsLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        myInfoShNumberAnsLbl.setForeground(new java.awt.Color(255, 255, 255));
        myInfoShNumberAnsLbl.setText("jLabel10");
        myInfoPnl.add(myInfoShNumberAnsLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 200, 30));

        myInfoClassAnsLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        myInfoClassAnsLbl.setForeground(new java.awt.Color(255, 255, 255));
        myInfoClassAnsLbl.setText("jLabel11");
        myInfoPnl.add(myInfoClassAnsLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 200, 30));

        myInfoGenderAnsLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        myInfoGenderAnsLbl.setForeground(new java.awt.Color(255, 255, 255));
        myInfoGenderAnsLbl.setText("jLabel12");
        myInfoPnl.add(myInfoGenderAnsLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 200, 30));

        myInfoGenderLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        myInfoGenderLbl.setForeground(new java.awt.Color(255, 255, 255));
        myInfoGenderLbl.setText("CİNSİYETİ");
        myInfoPnl.add(myInfoGenderLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 175, 30));

        getContentPane().add(myInfoPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel myInfoClassAnsLbl;
    private javax.swing.JLabel myInfoClassLbl;
    private javax.swing.JLabel myInfoGenderAnsLbl;
    private javax.swing.JLabel myInfoGenderLbl;
    private javax.swing.JLabel myInfoNameAnsLbl;
    private javax.swing.JLabel myInfoNameLbl;
    private javax.swing.JLabel myInfoPassAnsLbl;
    private javax.swing.JLabel myInfoPassLbl;
    private javax.swing.JLabel myInfoPhotoLbl;
    private javax.swing.JPanel myInfoPnl;
    private javax.swing.JLabel myInfoShNumberAnsLbl;
    private javax.swing.JLabel myInfoShNumberLbl;
    private javax.swing.JLabel myInfoTcnoAnsLbl;
    private javax.swing.JLabel myInfoTcnoLbl;
    // End of variables declaration//GEN-END:variables
    private DBConnection conn=new DBConnection();
    private  Connection con=conn.connDB();
    private  Statement st=null;
    private   ResultSet rs=null;
    private   PreparedStatement pt=null;

}
