/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUIs;
import static GUIs.LoginGUI.managerData;
import static GUIs.LoginGUI.studentData;
import static GUIs.LoginGUI.teacherData;
import java.awt.event.MouseEvent;
import Helper.DBConnection;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Kerem
 */
public class TeacherGUI extends javax.swing.JFrame {

    /**
     * Creates new form TeacherGUI
     */
    public TeacherGUI() {
        initComponents();
        
        try {
            
            st=con.createStatement();
            rs=st.executeQuery("SELECT * FROM teacher");
            while(rs.next()){
                tGuiWelcomeLbl.setText("Hoşgeldiniz " + teacherData[1]);
                if(teacherData[5].equals("ERKEK")){
                    tGuiLeftTopLbl.setIcon(new ImageIcon("C:\\swingDemos\\SchoolProject\\src\\Img\\erkek.png"));
                }
                else if(teacherData[5].equals("KADIN")){
                    tGuiLeftTopLbl.setIcon(new ImageIcon("C:\\swingDemos\\SchoolProject\\src\\Img\\kadin.png"));
                }
                else{
                    Helper.OptionPane.showMessage("error");
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(TeacherGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tGuiMainPnl = new javax.swing.JPanel();
        tGuiTopPnl = new javax.swing.JPanel();
        mGuiFlagLbl = new javax.swing.JLabel();
        tGuiLeftPnl = new javax.swing.JPanel();
        tGuiLeftTopPnl = new javax.swing.JPanel();
        tGuiLeftTopLbl = new javax.swing.JLabel();
        tGuiWelcomeLbl = new javax.swing.JLabel();
        tGuiLeftDownPnl = new javax.swing.JPanel();
        tGuiChangePassPnl = new javax.swing.JPanel();
        tGuiChangePassLbl = new javax.swing.JLabel();
        tGuiClassesPnl = new javax.swing.JPanel();
        tGuiClassesLbl = new javax.swing.JLabel();
        tGuiSelLesPnl = new javax.swing.JPanel();
        tGuiSelLesLbl = new javax.swing.JLabel();
        LogOutLbl1 = new javax.swing.JLabel();
        teacherDP = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 0, 0));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tGuiMainPnl.setBackground(new java.awt.Color(102, 0, 0));
        tGuiMainPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tGuiTopPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mGuiFlagLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIs/Images/teacher page 500X100 .png"))); // NOI18N
        tGuiTopPnl.add(mGuiFlagLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 100));

        tGuiMainPnl.add(tGuiTopPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 500, 100));

        tGuiLeftPnl.setBackground(new java.awt.Color(255, 51, 51));
        tGuiLeftPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tGuiLeftTopPnl.setBackground(new java.awt.Color(255, 51, 51));
        tGuiLeftTopPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tGuiLeftTopLbl.setBackground(new java.awt.Color(255, 51, 51));
        tGuiLeftTopLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tGuiLeftTopPnl.add(tGuiLeftTopLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 60));

        tGuiWelcomeLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tGuiWelcomeLbl.setForeground(new java.awt.Color(255, 255, 255));
        tGuiWelcomeLbl.setText("  Hoşgeldiniz");
        tGuiLeftTopPnl.add(tGuiWelcomeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 200, 90));

        tGuiLeftPnl.add(tGuiLeftTopPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 160));

        tGuiLeftDownPnl.setBackground(new java.awt.Color(255, 51, 51));
        tGuiLeftDownPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tGuiChangePassPnl.setBackground(new java.awt.Color(255, 51, 51));
        tGuiChangePassPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tGuiChangePassLbl.setBackground(new java.awt.Color(255, 51, 51));
        tGuiChangePassLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tGuiChangePassLbl.setForeground(new java.awt.Color(255, 255, 255));
        tGuiChangePassLbl.setText(" Şifre Değiştir");
        tGuiChangePassLbl.setOpaque(true);
        tGuiChangePassLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tGuiChangePassLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tGuiChangePassLblMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tGuiChangePassLblMousePressed(evt);
            }
        });
        tGuiChangePassPnl.add(tGuiChangePassLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 40));

        tGuiLeftDownPnl.add(tGuiChangePassPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 200, 40));

        tGuiClassesPnl.setBackground(new java.awt.Color(255, 51, 51));
        tGuiClassesPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tGuiClassesLbl.setBackground(new java.awt.Color(255, 51, 51));
        tGuiClassesLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tGuiClassesLbl.setForeground(new java.awt.Color(255, 255, 255));
        tGuiClassesLbl.setText(" Sınıflar");
        tGuiClassesLbl.setOpaque(true);
        tGuiClassesLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tGuiClassesLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tGuiClassesLblMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tGuiClassesLblMousePressed(evt);
            }
        });
        tGuiClassesPnl.add(tGuiClassesLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 40));

        tGuiLeftDownPnl.add(tGuiClassesPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, 40));

        tGuiSelLesPnl.setBackground(new java.awt.Color(255, 51, 51));
        tGuiSelLesPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tGuiSelLesLbl.setBackground(new java.awt.Color(255, 51, 51));
        tGuiSelLesLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tGuiSelLesLbl.setForeground(new java.awt.Color(255, 255, 255));
        tGuiSelLesLbl.setText(" Dersi Alan Öğrenciler");
        tGuiSelLesLbl.setOpaque(true);
        tGuiSelLesLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tGuiSelLesLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tGuiSelLesLblMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tGuiSelLesLblMousePressed(evt);
            }
        });
        tGuiSelLesPnl.add(tGuiSelLesLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 40));

        tGuiLeftDownPnl.add(tGuiSelLesPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 40));

        tGuiLeftPnl.add(tGuiLeftDownPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 200, 280));

        LogOutLbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogOutLbl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIs/Images/logout (4).png"))); // NOI18N
        LogOutLbl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LogOutLbl1MousePressed(evt);
            }
        });
        tGuiLeftPnl.add(LogOutLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 460, -1, -1));

        tGuiMainPnl.add(tGuiLeftPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 500));

        teacherDP.setBackground(new java.awt.Color(102, 0, 0));

        javax.swing.GroupLayout teacherDPLayout = new javax.swing.GroupLayout(teacherDP);
        teacherDP.setLayout(teacherDPLayout);
        teacherDPLayout.setHorizontalGroup(
            teacherDPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        teacherDPLayout.setVerticalGroup(
            teacherDPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        tGuiMainPnl.add(teacherDP, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 500, 400));

        getContentPane().add(tGuiMainPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tGuiClassesLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tGuiClassesLblMouseEntered
        tGuiClassesLbl.setBackground(new Color(102, 0, 0));
    }//GEN-LAST:event_tGuiClassesLblMouseEntered

    private void tGuiClassesLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tGuiClassesLblMouseExited
       tGuiClassesLbl.setBackground(new Color(255,51,51));
    }//GEN-LAST:event_tGuiClassesLblMouseExited

    private void tGuiSelLesLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tGuiSelLesLblMouseEntered
       tGuiSelLesLbl.setBackground(new Color(102, 0, 0));
    }//GEN-LAST:event_tGuiSelLesLblMouseEntered

    private void tGuiSelLesLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tGuiSelLesLblMouseExited
               tGuiSelLesLbl.setBackground(new Color(255,51,51));

    }//GEN-LAST:event_tGuiSelLesLblMouseExited

    private void tGuiChangePassLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tGuiChangePassLblMouseEntered
       tGuiChangePassLbl.setBackground(new Color(102, 0, 0));
    }//GEN-LAST:event_tGuiChangePassLblMouseEntered

    private void tGuiChangePassLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tGuiChangePassLblMouseExited
         tGuiChangePassLbl.setBackground(new Color(255,51,51));
    }//GEN-LAST:event_tGuiChangePassLblMouseExited

    private void tGuiClassesLblMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tGuiClassesLblMousePressed
       ClassesI classes=new ClassesI();
       teacherDP.removeAll();
       teacherDP.add(classes).setVisible(true);
    }//GEN-LAST:event_tGuiClassesLblMousePressed

    private void LogOutLbl1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutLbl1MousePressed
        LoginGUI logOut=new LoginGUI();
        logOut.setVisible(true);
        dispose();
    }//GEN-LAST:event_LogOutLbl1MousePressed

    private void tGuiChangePassLblMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tGuiChangePassLblMousePressed
      TeachChangePassI tcp=new TeachChangePassI();
      teacherDP.removeAll();
      teacherDP.add(tcp).setVisible(true);
    }//GEN-LAST:event_tGuiChangePassLblMousePressed

    private void tGuiSelLesLblMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tGuiSelLesLblMousePressed
      LessonTakersI LTI=new LessonTakersI();
      teacherDP.removeAll();
      teacherDP.add(LTI).setVisible(true);
    }//GEN-LAST:event_tGuiSelLesLblMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeacherGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeacherGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeacherGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeacherGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeacherGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LogOutLbl1;
    private javax.swing.JLabel mGuiFlagLbl;
    private javax.swing.JLabel tGuiChangePassLbl;
    private javax.swing.JPanel tGuiChangePassPnl;
    private javax.swing.JLabel tGuiClassesLbl;
    private javax.swing.JPanel tGuiClassesPnl;
    private javax.swing.JPanel tGuiLeftDownPnl;
    private javax.swing.JPanel tGuiLeftPnl;
    private javax.swing.JLabel tGuiLeftTopLbl;
    private javax.swing.JPanel tGuiLeftTopPnl;
    private javax.swing.JPanel tGuiMainPnl;
    private javax.swing.JLabel tGuiSelLesLbl;
    private javax.swing.JPanel tGuiSelLesPnl;
    private javax.swing.JPanel tGuiTopPnl;
    private javax.swing.JLabel tGuiWelcomeLbl;
    private javax.swing.JDesktopPane teacherDP;
    // End of variables declaration//GEN-END:variables
private DBConnection conn = new DBConnection();
private Connection con=conn.connDB();
   private Statement st = null;
   private ResultSet rs = null;
   private PreparedStatement pt = null;

}
