/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUIs;

import static GUIs.LoginGUI.teacherData;
import Helper.DBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Kerem
 */
public class TeachChangePassI extends javax.swing.JInternalFrame {

    /**
     * Creates new form ChangePassI
     */
    public TeachChangePassI() {
        initComponents();
         this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui=(BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
    }
    public void changePass(int id,String yeni){
         try {
                    st=con.createStatement();
                    pt=con.prepareStatement("UPDATE teacher SET password=? WHERE id=? ");
                    pt.setString(1, yeni);
                    pt.setInt(2, id);
                    pt.executeUpdate();
                    
                } catch (SQLException ex) {
                    Logger.getLogger(TeachChangePassI.class.getName()).log(Level.SEVERE, null, ex);
                }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPnl = new javax.swing.JPanel();
        oldPassLbl = new javax.swing.JLabel();
        oldPassTxt = new javax.swing.JTextField();
        newPassLbl = new javax.swing.JLabel();
        newPassAgainLbl = new javax.swing.JLabel();
        newPassTxt = new javax.swing.JTextField();
        newPassAgainTxt = new javax.swing.JTextField();
        changeBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 0, 0));
        setToolTipText("");
        setOpaque(true);
        setPreferredSize(new java.awt.Dimension(500, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPnl.setBackground(new java.awt.Color(102, 0, 0));
        mainPnl.setPreferredSize(new java.awt.Dimension(510, 400));
        mainPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        oldPassLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        oldPassLbl.setForeground(new java.awt.Color(255, 255, 255));
        oldPassLbl.setText("Eski Şifre");
        mainPnl.add(oldPassLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 200, 30));

        oldPassTxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        oldPassTxt.setForeground(new java.awt.Color(102, 0, 0));
        mainPnl.add(oldPassTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 200, 30));

        newPassLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        newPassLbl.setForeground(new java.awt.Color(255, 255, 255));
        newPassLbl.setText("Yeni Şifre");
        mainPnl.add(newPassLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 200, 30));

        newPassAgainLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        newPassAgainLbl.setForeground(new java.awt.Color(255, 255, 255));
        newPassAgainLbl.setText("Yeni Şifre Tekrar");
        mainPnl.add(newPassAgainLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 200, 30));

        newPassTxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        newPassTxt.setForeground(new java.awt.Color(102, 0, 0));
        mainPnl.add(newPassTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 200, 30));

        newPassAgainTxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        newPassAgainTxt.setForeground(new java.awt.Color(102, 0, 0));
        mainPnl.add(newPassAgainTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 200, 30));

        changeBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        changeBtn.setText("DEĞİŞTİR");
        changeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeBtnActionPerformed(evt);
            }
        });
        mainPnl.add(changeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 200, 30));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIs/Images/icons8_lock_32px.png"))); // NOI18N
        mainPnl.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 60, 50));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIs/Images/icons8_lock_32px.png"))); // NOI18N
        mainPnl.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 60, 50));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIs/Images/icons8_lock_32px.png"))); // NOI18N
        mainPnl.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 60, 50));

        getContentPane().add(mainPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeBtnActionPerformed
      if(oldPassTxt.getText().equals("")||newPassTxt.getText().equals("")||newPassAgainTxt.getText().equals("")){
          Helper.OptionPane.showMessage("fill");
      }
      else{
        
        if(oldPassTxt.getText().equals(teacherData[3])){
            if(newPassTxt.getText().equals(newPassAgainTxt.getText())){
                 Helper.OptionPane.showMessage("success");
                    changePass((int) teacherData[0],newPassTxt.getText());
                try {
                   
                    st=con.createStatement();
                    rs=st.executeQuery("SELECT * FROM teacher WHERE tcno="+teacherData[2]);
                    while(rs.next()){
                        teacherData[3]=rs.getString("password");
                    }
                    oldPassTxt.setText(null);
                    newPassTxt.setText(null);
                    newPassAgainTxt.setText(null);
                    
                } catch (SQLException ex) {
                    Logger.getLogger(TeachChangePassI.class.getName()).log(Level.SEVERE, null, ex);
                }
               
            }
            
            else{
                JOptionPane.showMessageDialog(null, "Yeni Şifre ile Tekrar Girilen Şifre Eşleşmiyor","HATA!",JOptionPane.WARNING_MESSAGE);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Eski Şifre Yanlış","HATA!",JOptionPane.WARNING_MESSAGE);
        }
      }
    }//GEN-LAST:event_changeBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changeBtn;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel mainPnl;
    private javax.swing.JLabel newPassAgainLbl;
    private javax.swing.JTextField newPassAgainTxt;
    private javax.swing.JLabel newPassLbl;
    private javax.swing.JTextField newPassTxt;
    private javax.swing.JLabel oldPassLbl;
    private javax.swing.JTextField oldPassTxt;
    // End of variables declaration//GEN-END:variables
private DBConnection conn=new DBConnection();
   private Connection con=conn.connDB();
   private Statement st=null;
   private ResultSet rs=null;
   private PreparedStatement pt=null;


}
